version: '3.3'
services:
  reactjs:
    container_name: time_your_task_front
    image: 'node:latest'
    working_dir: /home/reactjs/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm i && npm start'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/home/reactjs/app'